### ISSUE TITLE
Fatal Error!

### ISSUE THREAD

**Issue by RualFX** [fmohican/NosRegister#30]
Fatal error: Uncaught Error: Call to undefined function sqlsrv_connect() in C:\xampp\htdocs\config.php:58 Stack trace: #0 C:\xampp\htdocs\index.php(2): require_once() #1 {main} thrown in C:\xampp\htdocs\config.php on line 58

So, i try to use the register on Localhost and Windows Authentication.

Why do i get this error?!

**Comment by fmohican** [comment]
In order to use sqlsvr you need to install mssql extension you can find more there :

http://php.net/manual/en/mssql.installation.php
https://www.microsoft.com/en-us/download/details.aspx?id=20098 (install, copy .dll to php/ext ) and add to php.ini
Microsoft Drivers for PHP for SQL Server : https://github.com/Microsoft/msphpsql (i don't know if this will help you)
php.ini to add

extension=php_pdo_sqlsrv_7_nts.dll
extension=php_sqlsrv_7_nts.dll
extension=php_pdo_sqlsrv_7_nts_x64.dll
extension=php_pdo_sqlsrv_7_nts_x86.dll
extension=php_pdo_sqlsrv_7_ts_x64.dll
extension=php_pdo_sqlsrv_7_ts_x86.dll
extension=php_sqlsrv_7_nts_x64.dll
extension=php_sqlsrv_7_nts_x86.dll
extension=php_sqlsrv_7_ts_x64.dll
extension=php_sqlsrv_7_ts_x86.dll

**Comment by fmohican** [comment]
@RualFX i will be very happy if ppl will read what i wirite
